# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Python in Lisp
tagline:          'A Python to Common Lisp translator'
description:      'A project and blog dedicated to bringing Python libraries to Common Lisp.'
url:              https://github.com/felipeochoa/py-lisp/
baseurl:          /py-lisp

author:
  name:           'Felipe Ochoa'
  url:            https://www.linkedin.com/in/felipeochoa

paginate:         5

# Custom vars
version:          master

github:
  repo:           https://github.com/felipeochoa/py-lisp
