# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Python is not Lisp
tagline:          'A Python to Common Lisp translator'
description:      'A blog and project dedicated to bringing Python batteries to Common Lisp.'
url:              https://github.com/felipeochoa/py-lisp/
baseurl:          /py-lisp/

author:
  name:           'Felipe Ochoa'
  url:            https://www.linkedin.com/in/felipeochoa

paginate:         5

# Custom vars
version:          master

github:
  repo:           https://github.com/felipeochoa/py-lisp
